
version: "3.3"

services:

    mpd:
        hostname: mpd
        image: piradio_mpd
        ports:
            - "6600:6600"
            #- "8800:8800"
        volumes:
            - ${MUSIC_DIR}:/local/music
            - ${PLAYLIST_DIR}:/local/playlists
            - ${MPD_DB_DIR}:/var/lib/mpd
        devices:
            - /dev/snd
        restart: unless-stopped
        env_file:
            - .env

        
    db:
        hostname: db
        image: arm32v6/postgres:12.2-alpine
        volumes:
            - dbdata:/var/lib/postgresql/data
        env_file:
            - .env
        restart: unless-stopped
            
    web:
        hostname: web
        image: piradio_web
        env_file:
            - .env
        environment:
            - PYTHON_PATH=/code
            - POSTGRES_SERVICE=db
            - POSTGRES_PORT=5432
            - MPD_HOST=mpd
            - MPD_PORT=6600
        depends_on:
            - db
            - mpd
        devices:
            - /dev/snd
        volumes:
            - wwwsocket:/tmp/piradio
            # store log files externally
            - log:/var/log/uwsgi
            # This might be removed in "real" production run.
            # For testing, this might be better as you won't need to run docker build the whole time.
            - ./code:/code
            - static:/code/static
        working_dir: /code
        ports:
            # This is for debugging.
            # Use 
            #   docker-compose run web bash
            #   cd /code/piremote
            #   ./manage.py runserver 0.0.0.0:8000
            # for testing.
            - "8000:8000"
        restart: unless-stopped
        

    
    
    nginx:
        hostname: piradio
        image: arm32v6/nginx:1.17-alpine
        env_file:
            - .env
        depends_on:
            - web
        ports:
            - "80:80"
        volumes:
            - ./files/nginx/piradio.conf:/etc/nginx/conf.d/default.conf
            - wwwsocket:/tmp/piradio
            - static:/code/static
        restart: unless-stopped
        
volumes:
    # Keep SQL database
    dbdata:
    # place unix socker for access nginx->uwsgi(django) here
    wwwsocket:
    # some error logs
    log:
    # static files
    static:
