
version: "3.3"

services:

    mpd:
        image: piradio_mpd
        ports:
            - "6600:6600"
            - "8800:8800" 
        volumes:
            - ${MUSIC_DIR}:/local/music
            - ${PLAYLIST_DIR}:/local/playlists
            - ${MPD_DB_DIR}:/var/lib/mpd
        devices:
            - /dev/snd
        restart: unless-stopped
        environment:
            - .env

        
    db:
        image: arm32v6/postgres
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment:
            - .env
            
    web:
        image: piradio_web
        environment:
            - .env
            - PYTHON_PATH=/code
            - POSTGRES_SERVICE=db
            - POSTGRES_PORT=5432
        depends_on:
            - db
            - mpd
        volumes:
            - wwwsocket:/tmp/simweb
            # store log files externally
            - log:/var/log/uwsgi
            - ./code:/code
        working_dir: /code
        

    
    
    nginx:
        image: arm32v6/nginx
        environment:
            - .env
        depends_on:
            - web
        ports:
            - 80:80
        volumes:
            - ./files/nginx:/etc/nginx/conf.d

volumes:
    # Keep SQL database
    dbdata:
    # place unix socker for access nginx->uwsgi(django) here
    wwwsocket:
    # some error logs
    log:

