 

FROM arm32v6/alpine:3.11.5 AS web

ENV LC_ALL=en_US.UTF-8
ENV PYTHON_PATH=/code
RUN apk update && apk upgrade && \ 
    apk add bash mpc python3 python3-dev postgresql-dev alsa-utils npm gcc musl-dev linux-headers \
        python3-dev build-base linux-headers pcre-dev libc-dev musl memcached libmemcached-dev zlib-dev \
        make libffi-dev libxslt-dev libxml2 libxml2-dev py3-lxml
        
RUN mkdir /code
WORKDIR /code
    
COPY code/requirements.txt /code
RUN npm install --global coffeescript sass yuglify
RUN pip3 install --upgrade pip setuptools
RUN pip3 install -r /code/requirements.txt

ADD code /code

COPY files/web/run_service.sh /usr/local/bin
RUN chmod 755 /usr/local/bin/run_service.sh
COPY files/web/uwsgi.ini /etc/uwsgi/uwsgi.ini

COPY .env /root/.env
COPY files/web/compress.sh /root/
RUN /root/compress.sh

EXPOSE 8000
CMD ["/usr/local/bin/run_service.sh"]


FROM arm32v6/nginx:1.17-alpine AS nginx

RUN mkdir -pv /static
COPY files/nginx/piradio.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]
