 

FROM arm32v6/alpine:3.11.5

COPY qemu-arm-static /usr/bin/qemu-arm-static

ENV LC_ALL=en_US.UTF-8

RUN apk update && apk upgrade && \ 
    apk add bash mpc python3 python3-dev postgresql-dev alsa-utils npm

RUN mkdir /code
WORKDIR /code
    
COPY code/requirements.txt /code
RUN npm install --global coffeescript sass
RUN pip3 install --upgrade pip setuptools
RUN pip3 install -r /code/requirements.txt


ADD code /code

CMD ["/bin/bash"]
