version: "3.3"

services:

    web:
        environment:
            - DEBUG=1
        volumes:
            static: /code/static
            command: cd /code && ./manage.py migrate && ./manage.py compress --extension=pug --force && ./manage.py collectstatic --no-input && uwsgi --ini /etc/uwsgi/uwsgi.ini

    nginx:
        volumes:
            static: /code/static


volumes:
    static:


