version: "3.3"

services:

    web:
        environment:
            - COLLECT=1
        volumes:
            - ./code:/code
            - static:/code/static

    nginx:
        volumes:
            - static:/code/static

volumes:
    static:


