
version: "3.3"

services:

    mpd:
        hostname: mpd
        image: piradio_mpd
        ports:
            - "6600:6600"
            #- "8800:8800"
        volumes:
            - ${MUSIC_DIR}:/local/music
            - ${PLAYLIST_DIR}:/local/playlists
            - ${MPD_DB_DIR}:/var/lib/mpd
        devices:
            - /dev/snd
        restart: unless-stopped
        env_file:
            - .env

        
    db:
        hostname: db
        image: arm32v6/postgres:12.2-alpine
        volumes:
            - dbdata:/var/lib/postgresql/data
        env_file:
            - .env
        restart: unless-stopped
            
    web:
        hostname: web
        image: piradio_web
        env_file:
            - .env
        depends_on:
            - db
            - mpd
        devices:
            - /dev/snd
        volumes:
            - wwwsocket:/tmp/piradio
            # store log files externally
            - log:/var/log/uwsgi
            # store static files externally
            - static:/static
        working_dir: /code
        ports:
            # This is for debugging.
            # Use 
            #   docker-compose run web bash
            #   cd /code/piremote
            #   ./manage.py runserver 0.0.0.0:8000
            # for testing.
            - "8000:8000"
        restart: unless-stopped
    
    nginx:
        hostname: piradio
        image: piradio_nginx
        env_file:
            - .env
        depends_on:
            - web
        ports:
            - "80:80"
        volumes:
            - wwwsocket:/tmp/piradio
            - static:/static
        restart: unless-stopped
        
volumes:
    # Keep SQL database
    dbdata:
    # place unix socker for access nginx->uwsgi(django) here
    wwwsocket:
    # some error logs
    log:
    # static files collected by django
    static: