 

FROM arm32v6/alpine:3.11.5


ENV LC_ALL=en_US.UTF-8

RUN apk update && apk upgrade && \ 
    apk add bash mpc python3 python3-dev postgresql-dev alsa-utils npm gcc musl-dev linux-headers

RUN mkdir /code
WORKDIR /code
    
COPY code/requirements.txt /code
RUN npm install --global coffeescript sass
RUN pip3 install --upgrade pip setuptools
RUN pip3 install -r /code/requirements.txt

ADD code /code

COPY files/web/run_service.sh /usr/local/bin
RUN chmod 755 /usr/local/bin/run_service.sh

RUN mkdir -p /etc/uwsgi/vassals
COPY files/web/uwsgi.ini /etc/uwsgi
COPY files/web/piradio.ini /etc/uwsgi/vassals



CMD ["/bin/bash"]
