
FROM arm32v6/alpine:3.11.5

# COPY qemu-arm-static /usr/bin/qemu-arm-static

ENV LC_ALL=en_US.UTF-8

RUN apk update && apk upgrade && \ 
    apk add bash mpd mpc

COPY files/mpd/mpd.conf /etc/mpd.conf
VOLUME /var/lib/mpd

EXPOSE 6600

CMD ["mpd", "--stdout", "--no-daemon"]
